function(PACKAGE)
    unset(YICES_PACKAGE)
    if (APPLE)
        set(YICES_PACKAGE ${CMAKE_SOURCE_DIR}/src/contrib/yices-2.5.1-x86_64-apple-darwin15.6.0-static-gmp.tar.gz PARENT_SCOPE)
        set(YICES_INCLUDE_DIR_SUFFIX /include PARENT_SCOPE)
        set(YICES_LIBRARY_SUFFIX /lib/libyices.2.dylib PARENT_SCOPE)
    elseif (UNIX)
        set(YICES_PACKAGE ${CMAKE_SOURCE_DIR}/src/contrib/yices-2.5.1-x86_64-unknown-linux-gnu-static-gmp.tar.gz PARENT_SCOPE)
        set(YICES_INCLUDE_DIR_SUFFIX /include PARENT_SCOPE)
        set(YICES_LIBRARY_SUFFIX /lib/libyices.so.2.5.1 PARENT_SCOPE)
    endif ()
endfunction()