function(PACKAGE)
    unset(Z3_PACKAGE)
    if (APPLE)
        set(Z3_PACKAGE ${CMAKE_SOURCE_DIR}/src/contrib/z3-4.4.1-x64-osx-10.11.zip PARENT_SCOPE)
        set(Z3_INCLUDE_DIR_SUFFIX /include PARENT_SCOPE)
        set(Z3_LIBRARY_SUFFIX /bin/libz3.a PARENT_SCOPE)
    elseif (UNIX)
        set(Z3_PACKAGE ${CMAKE_SOURCE_DIR}/src/contrib/z3-4.4.1-x64-debian-8.2.zip PARENT_SCOPE)
        set(Z3_INCLUDE_DIR_SUFFIX /include PARENT_SCOPE)
        set(Z3_LIBRARY_SUFFIX /bin/libz3.a PARENT_SCOPE)
    endif ()
endfunction()