#line 2 "smtlexer.cc"

#line 4 "smtlexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer smt_create_buffer
#define yy_delete_buffer smt_delete_buffer
#define yy_flex_debug smt_flex_debug
#define yy_init_buffer smt_init_buffer
#define yy_flush_buffer smt_flush_buffer
#define yy_load_buffer_state smt_load_buffer_state
#define yy_switch_to_buffer smt_switch_to_buffer
#define yyin smtin
#define yyleng smtleng
#define yylex smtlex
#define yylineno smtlineno
#define yyout smtout
#define yyrestart smtrestart
#define yytext smttext
#define yywrap smtwrap
#define yyalloc smtalloc
#define yyrealloc smtrealloc
#define yyfree smtfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE smtrestart(smtin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t smtleng;

extern FILE *smtin, *smtout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE smtlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-smtlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < smtleng; ++yyl )\
                    if ( smttext[yyl] == '\n' )\
                        --smtlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up smttext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up smttext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via smtrestart()), so that the user can continue scanning by
	 * just pointing smtin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when smttext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t smtleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow smtwrap()'s to do buffer switches
 * instead of setting up a fresh smtin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void smtrestart (FILE *input_file  );
void smt_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE smt_create_buffer (FILE *file,int size  );
void smt_delete_buffer (YY_BUFFER_STATE b  );
void smt_flush_buffer (YY_BUFFER_STATE b  );
void smtpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void smtpop_buffer_state (void );

static void smtensure_buffer_stack (void );
static void smt_load_buffer_state (void );
static void smt_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER smt_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE smt_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE smt_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE smt_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *smtalloc (yy_size_t  );
void *smtrealloc (void *,yy_size_t  );
void smtfree (void *  );

#define yy_new_buffer smt_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        smtensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            smt_create_buffer(smtin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        smtensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            smt_create_buffer(smtin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define smtwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *smtin = (FILE *) 0, *smtout = (FILE *) 0;

typedef int yy_state_type;

extern int smtlineno;

int smtlineno = 1;

extern char *smttext;
#define yytext_ptr smttext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up smttext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	smtleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[360] =
    {   0,
        0,    0,    0,    0,    0,    0,   96,   94,    1,    1,
       94,   85,   84,   93,   27,   24,   25,   84,   28,   80,
       93,   94,   32,   29,   33,   86,   84,   84,   84,   84,
       84,   16,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   88,   26,   90,
       91,   90,   90,   92,   95,    0,   85,   84,   84,   86,
       80,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,   30,   31,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   67,   84,   84,   84,   84,   84,   84,

       84,   84,   89,   87,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   84,   84,   84,   84,   18,   84,
       66,   84,   84,   81,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   69,
       84,   75,   72,   68,   84,   84,   84,   84,   84,   84,
       70,   84,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   84,   84,   84,   84,   17,   84,   78,   79,
        0,   84,   84,   84,   84,   84,   84,   84,   84,   45,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   71,   84,   84,   84,   84,

       84,   84,   84,   73,   84,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   20,   84,   84,   21,   84,
        0,   48,   44,   84,   84,   84,   50,   51,   47,   84,
       37,   35,   54,   36,   34,   84,   49,   84,   41,   39,
       40,   38,   84,   46,   84,   84,   84,   74,   84,   84,
       84,   84,   84,   84,   60,   84,    0,    0,    0,    0,
        0,    0,   11,   15,    0,    0,   19,   84,   84,   82,
       53,   83,   52,   57,   55,   58,   56,   42,   84,   84,
       84,   84,   23,   84,   59,   84,   84,    0,    0,    0,
        0,    0,    0,    0,    0,   10,   12,   22,   84,   84,

       43,   84,   65,   84,   84,   84,    0,    0,    0,    0,
        0,    0,    8,    0,   84,   77,   84,   84,   84,   84,
       84,    0,   13,    0,    0,    0,    0,    0,    3,   84,
       84,   84,   84,   84,    0,    0,    6,    0,    0,    0,
       84,   84,   84,   84,   84,    7,   14,    5,    4,    0,
       84,   63,   84,   61,   62,    9,   76,   64,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    1,    6,    7,
        7,    8,    9,    1,   10,   11,   12,   13,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,   21,    1,   22,   23,   11,   11,   24,   11,
       11,   11,   25,   11,   11,   11,   11,   11,   11,   11,
       11,   26,   11,   11,   27,   28,   11,   11,   11,   11,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   11,   42,   43,   44,   45,
       46,   47,   11,   48,   49,   50,   51,   52,   11,   53,
       54,   55,   56,    1,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    2,    1,    1,    3,    4,    1,    1,    1,    1,
        5,    1,    5,    5,    5,    1,    1,    1,    1,    1,
        6,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[368] =
    {   0,
        0,    0,   56,   58,    0,    0,  438, 1291, 1291, 1291,
        0,    0,    0, 1291, 1291, 1291, 1291,   58, 1291,   60,
       83,  426,  408, 1291,  406,    0,   62,   64,   66,   72,
       85,   90,   93,  102,  124,  128,  130,  135,  141,  152,
      154,  159,  166,  161,  171,  188,  199, 1291, 1291, 1291,
     1291, 1291,  364, 1291, 1291,  414,    0,    0,  208,    0,
      210,  367,  375,  365,  347,  352,  351,  341,  335,   30,
      372, 1291, 1291, 1291,  212,  216,  221,  233,  235,  238,
      240,  242,  288,  244,  246,  265,  267,  270,  276,  299,
      306,  319,  323,  330,  342,  344,  347,  349,  351,  353,

      355,  361, 1291, 1291,  322,  314,  324,  295,  294,  288,
      291,  276,  272,  286,  372,  374,  378,  380,  386,  405,
      407,  409,  418,  428,  414,  431,  440,  448,  450,  459,
      503,  434,  470,  462,  473,  496,  498,  500,  505,  507,
      509,  527,  532,  535,  552,  554,  556,  558,  560,  562,
      564,  585,  267,  280,  278,  265,  262,  263,  258,  261,
      242,  237,  589,  591,  595,  599,  608,  613,  616,  618,
       87,  620,  630,  639,  641,  643,  649,  652,  663,  666,
      669,  672,  675,  683,  693,  695,  700,  702,  706,  726,
      719,  729,  732,  739,  743,  749,  753,  760,  763,  770,

      773,  777,  781,  783,  794,  240,  238,  223,  229,  206,
      207,  218,  186,  197,  179,  800,  806,  808,  811,  817,
      265,  819,  825,  828,  830,  842,  849,  851,  853,  859,
      861,  863,  872,  880,  882,  886,  889,  891,  893,  899,
      903,  910,  912,  916,  920,  923,  929,  933,  940,  942,
      946,  952,  954,  960,  966,  977,  181,  164,  173,  106,
      163,  154, 1291, 1291,  162,  148,  979,  985,  987, 1291,
      989, 1010,  996, 1006, 1013, 1016, 1020, 1023, 1027, 1033,
     1037, 1040, 1044, 1046, 1050, 1054, 1058,  146,  147,  139,
      137,  138,  138,  148,  128, 1291, 1291, 1063, 1067, 1071,

     1075, 1080, 1085, 1088, 1092, 1097,  122,  107,  109,  105,
      111,   94, 1291,   94, 1099, 1111, 1117, 1119, 1122, 1124,
     1128,   85, 1291,   77,   76,   76,   54,   70, 1145, 1147,
     1153, 1164, 1166, 1171,   52,   40, 1291,   43,   40,   34,
     1173, 1175, 1177, 1183, 1194, 1291, 1291, 1291, 1291,   45,
     1200, 1202, 1207, 1221, 1226, 1291, 1228, 1230, 1291, 1257,
     1263, 1268, 1271, 1273, 1276, 1282, 1284
    } ;

static yyconst flex_int16_t yy_def[368] =
    {   0,
      359,    1,  360,  360,  361,  361,  359,  359,  359,  359,
      362,  363,  364,  359,  359,  359,  359,  365,  359,  365,
      359,  366,  359,  359,  359,  367,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  359,  359,  359,
      359,  359,  359,  359,  359,  362,  363,  364,  365,  367,
      365,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      366,  359,  359,  359,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  131,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  365,  365,  365,  365,  365,  365,  365,  365,
      359,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  365,  365,  365,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  365,  365,  365,  365,  365,
      359,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  365,  365,  365,  359,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  359,  359,  359,  359,
      359,  359,  359,  359,  365,  365,  365,  365,  365,  365,
      365,  359,  359,  359,  359,  359,  359,  359,  365,  365,
      365,  365,  365,  365,  359,  359,  359,  359,  359,  359,
      365,  365,  365,  365,  365,  359,  359,  359,  359,  359,
      365,  365,  365,  365,  365,  359,  365,  365,    0,  359,
      359,  359,  359,  359,  359,  359,  359
    } ;

static yyconst flex_int16_t yy_nxt[1350] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   18,   14,    8,
       14,   18,   33,   34,   35,   36,   37,   38,   18,   18,
       39,   18,   40,   18,   41,   42,   18,   43,   44,   45,
       18,   18,   46,   18,   47,   48,   14,   49,   51,   52,
       51,   52,   57,   58,   57,   58,   57,   58,   57,   58,
       57,   58,   61,   61,   61,  113,   57,   58,   60,  114,
       60,  356,   60,  350,   60,   53,   60,   53,  349,   57,
       58,  348,   60,  347,   57,   58,  346,   57,   58,  221,

      221,  221,  340,  339,   76,   60,   57,   58,   77,   75,
       60,  338,   54,   60,   54,   62,   78,   63,   64,   65,
       66,   79,   60,   67,  337,   68,  336,   69,   57,   58,
      335,   70,   57,   58,   57,   58,  328,   80,   81,   57,
       58,  327,   82,  291,   60,   57,   58,  326,   60,  325,
       60,  324,  292,   83,  293,   60,   57,   58,   57,   58,
      323,   60,  322,   57,   58,   57,   58,   87,   85,   84,
       57,   58,   60,  314,   60,   57,   58,   88,   89,   60,
      313,   60,   86,  312,   90,  311,   60,  310,   92,  309,
       91,   60,   57,   58,  308,  307,  297,   97,  296,   93,

      295,   98,   95,   57,   58,  294,   94,  290,   60,  289,
       99,   96,   57,   58,   57,   58,   57,   58,  100,   60,
       57,   58,   61,   61,   61,   57,   58,  288,   60,  266,
       60,  265,   60,  101,  264,  102,   60,   57,   58,   57,
       58,   60,   57,   58,   57,   58,   57,   58,   57,   58,
       57,   58,  263,   60,  262,   60,  261,  117,   60,  115,
       60,  260,   60,  259,   60,  116,   60,  120,  118,   57,
       58,   57,   58,  121,   57,   58,  258,  221,  221,  221,
       57,   58,  119,  257,  122,   60,  215,   60,  134,  214,
       60,  123,   57,   58,  135,  270,   60,  213,  212,  211,

      124,  124,  124,   57,   58,  210,  138,  139,   60,  137,
       57,   58,  209,  140,  136,  208,  207,  206,  162,   60,
      125,  126,  161,   57,   58,  160,   60,   57,   58,  159,
      127,  128,  129,  130,   57,   58,  131,  158,  132,   60,
      133,  157,  142,   60,  156,  141,   57,   58,   57,   58,
       60,   57,   58,   57,   58,   57,   58,   57,   58,   57,
       58,  155,   60,  154,   60,   57,   58,   60,  143,   60,
      153,   60,  144,   60,   72,   60,   57,   58,   57,   58,
      112,   60,   57,   58,   57,   58,  111,  148,  145,  147,
       57,   58,   60,  146,   60,  110,  149,  109,   60,  108,

       60,  164,  151,  150,  163,  107,   60,  106,  152,   57,
       58,   57,   58,   57,   58,  105,  166,  104,   57,   58,
      103,  165,   57,   58,   74,   60,   73,   60,   72,   60,
      169,  170,   57,   58,   60,   57,   58,  359,   60,  359,
      124,  124,  124,  168,   57,   58,  359,  167,   60,  172,
      359,   60,   57,   58,   57,   58,  171,  359,  173,  359,
       60,  359,  174,   57,   58,  359,   57,   58,   60,  187,
       60,  175,  188,   59,   57,   58,  189,   57,   58,   60,
      359,  190,   60,  359,   59,  359,  178,  359,  176,  359,
       60,  359,  359,   60,  359,  179,  192,  359,  177,  359,

       57,   58,   57,   58,   57,   58,  180,   57,   58,   57,
       58,   57,   58,   57,   58,  191,   60,  359,   60,  359,
       60,  359,  193,   60,  359,   60,  359,   60,  359,   60,
      359,   57,   58,  359,  359,  359,   57,   58,  181,   57,
       58,  182,  183,  194,  359,  184,  195,   60,  359,  196,
      185,  198,   60,  186,  197,   60,   57,   58,   57,   58,
       57,   58,   57,   58,   57,   58,   57,   58,   57,   58,
      359,  359,   60,  359,   60,  359,   60,  359,   60,  359,
       60,  359,   60,  359,   60,  359,  200,  359,  199,   57,
       58,  359,  201,   57,   58,   57,   58,  359,  204,   57,

       58,  359,  202,   57,   58,   60,  359,  203,  359,   60,
      359,   60,   57,   58,  359,   60,  359,   57,   58,   60,
       57,   58,   57,   58,   57,   58,  359,  217,   60,  359,
      205,  218,  359,   60,   57,   58,   60,  359,   60,  359,
       60,  359,  216,   57,   58,   57,   58,   57,   58,  359,
       60,  219,  220,   57,   58,  222,   57,   58,  359,   60,
      359,   60,  359,   60,  359,  223,  359,   57,   58,   60,
       57,   58,   60,   57,   58,  359,   57,   58,  224,   57,
       58,  359,  226,   60,  359,  225,   60,   57,   58,   60,
      228,  227,   60,  359,  359,   60,  359,   57,   58,   57,

       58,  359,  359,   60,   57,   58,   57,   58,  231,  230,
       57,   58,  229,   60,  359,   60,  359,  233,  359,  234,
       60,  232,   60,   57,   58,  359,   60,  359,  237,  236,
       57,   58,  235,   57,   58,  359,   57,   58,  239,   60,
      238,  359,  241,   57,   58,  359,   60,   57,   58,   60,
      359,  240,   60,   57,   58,  242,  359,   57,   58,   60,
      359,  245,  243,   60,   57,   58,  244,   57,   58,   60,
      359,  247,  246,   60,   57,   58,  359,   57,   58,  248,
       60,   57,   58,   60,  359,   57,   58,   57,   58,  359,
       60,  359,  249,   60,  359,  251,  359,   60,   57,   58,

      250,   60,  359,   60,   57,   58,  359,  253,  254,  359,
       57,   58,   57,   58,   60,   57,   58,  255,  359,  252,
       60,   57,   58,   57,   58,  256,   60,  359,   60,   57,
       58,   60,   57,   58,   57,   58,  359,   60,  359,   60,
      267,  359,  272,  272,  359,   60,   57,   58,   60,  359,
       60,  359,  268,   57,   58,   57,   58,   57,   58,  359,
      269,  359,   60,   57,   58,   57,   58,   57,   58,   60,
      359,   60,  359,   60,  359,  271,   57,   58,  359,   60,
      359,   60,  359,   60,   57,   58,   57,   58,  359,  273,
       57,   58,   60,   57,   58,   57,   58,   57,   58,  359,

       60,  359,   60,   57,   58,  359,   60,   57,   58,   60,
      274,   60,  359,   60,   57,   58,   57,   58,  359,   60,
       57,   58,  359,   60,   57,   58,  359,   57,   58,  275,
       60,  359,   60,   57,   58,  359,   60,   57,   58,  359,
       60,  359,  276,   60,   57,   58,   57,   58,  359,   60,
       57,   58,  359,   60,  359,  277,   57,   58,   57,   58,
       60,  359,   60,  280,   57,   58,   60,  279,  359,  278,
       57,   58,   60,  359,   60,  359,  281,  359,  282,  359,
       60,   57,   58,   57,   58,  359,   60,  359,  284,   57,
       58,   57,   58,   57,   58,  283,  286,   60,  359,   60,

       57,   58,  359,  285,  359,   60,  359,   60,  359,   60,
       57,   58,  359,  287,   57,   58,   60,   57,   58,  299,
       57,   58,  272,  272,   57,   58,   60,   57,   58,  359,
       60,   57,   58,   60,  298,  359,   60,   57,   58,  359,
       60,   57,   58,   60,   57,   58,  359,   60,   57,   58,
       57,   58,  359,   60,   57,   58,  359,   60,   57,   58,
       60,  300,   57,   58,   60,  359,   60,   57,   58,  359,
       60,   57,   58,  359,   60,   57,   58,  304,   60,   57,
       58,  302,  301,   60,   57,   58,  359,   60,  303,   57,
       58,   60,   57,   58,  359,   60,   57,   58,  359,  359,

       60,   57,   58,   57,   58,   60,  305,  359,   60,  359,
      306,  317,   60,  359,  315,   57,   58,   60,  359,   60,
      316,   57,   58,   57,   58,  359,   57,   58,   57,   58,
      318,   60,   57,   58,  359,  319,  359,   60,  359,   60,
      329,  320,   60,  359,   60,  359,  321,  359,   60,   57,
       58,   57,   58,  330,  359,  331,  359,   57,   58,  359,
      333,  359,  332,  359,  334,   60,  359,   60,   57,   58,
       57,   58,  359,   60,  359,   57,   58,   57,   58,   57,
       58,   57,   58,  359,   60,  359,   60,   57,   58,  341,
      342,   60,  359,   60,  359,   60,  359,   60,   57,   58,

      359,  359,  343,   60,   57,   58,   57,   58,  359,  359,
      344,   57,   58,  359,   60,  345,  353,  359,  354,  359,
       60,  351,   60,  359,  352,   57,   58,   60,  359,  355,
       57,   58,   57,   58,   57,   58,  357,  359,  359,  359,
      359,   60,  359,  359,  359,  359,   60,  359,   60,  359,
       60,  359,  359,  359,  359,  359,  358,   50,   50,   50,
       50,   50,   50,   55,   55,   55,   55,   55,   55,   56,
      359,   56,   56,   57,  359,   57,   58,   58,   59,   59,
       59,   59,   71,   71,   71,   71,   71,   71,   60,   60,
        7,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359
    } ;

static yyconst flex_int16_t yy_chk[1350] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,   18,   18,   20,   20,   27,   27,   28,   28,
       29,   29,   20,   20,   20,   70,   30,   30,   18,   70,
       20,  350,   27,  340,   28,    3,   29,    4,  339,   31,
       31,  338,   30,  336,   32,   32,  335,   33,   33,  171,

      171,  171,  328,  327,   28,   31,   34,   34,   29,   27,
       32,  326,    3,   33,    4,   21,   30,   21,   21,   21,
       21,   31,   34,   21,  325,   21,  324,   21,   35,   35,
      322,   21,   36,   36,   37,   37,  314,   33,   34,   38,
       38,  312,   34,  260,   35,   39,   39,  311,   36,  310,
       37,  309,  260,   34,  260,   38,   40,   40,   41,   41,
      308,   39,  307,   42,   42,   44,   44,   38,   36,   35,
       43,   43,   40,  295,   41,   45,   45,   38,   39,   42,
      294,   44,   37,  293,   39,  292,   43,  291,   40,  290,
       39,   45,   46,   46,  289,  288,  266,   44,  265,   41,

      262,   44,   43,   47,   47,  261,   42,  259,   46,  258,
       44,   43,   59,   59,   61,   61,   75,   75,   45,   47,
       76,   76,   61,   61,   61,   77,   77,  257,   59,  215,
       61,  214,   75,   46,  213,   47,   76,   78,   78,   79,
       79,   77,   80,   80,   81,   81,   82,   82,   84,   84,
       85,   85,  212,   78,  211,   79,  210,   77,   80,   75,
       81,  209,   82,  208,   84,   76,   85,   79,   78,   86,
       86,   87,   87,   80,   88,   88,  207,  221,  221,  221,
       89,   89,   78,  206,   81,   86,  162,   87,   84,  161,
       88,   82,   83,   83,   85,  221,   89,  160,  159,  158,

       83,   83,   83,   90,   90,  157,   88,   89,   83,   87,
       91,   91,  156,   89,   86,  155,  154,  153,  114,   90,
       83,   83,  113,   92,   92,  112,   91,   93,   93,  111,
       83,   83,   83,   83,   94,   94,   83,  110,   83,   92,
       83,  109,   91,   93,  108,   90,   95,   95,   96,   96,
       94,   97,   97,   98,   98,   99,   99,  100,  100,  101,
      101,  107,   95,  106,   96,  102,  102,   97,   92,   98,
      105,   99,   93,  100,   71,  101,  115,  115,  116,  116,
       69,  102,  117,  117,  118,  118,   68,   98,   95,   97,
      119,  119,  115,   96,  116,   67,   99,   66,  117,   65,

      118,  116,  101,  100,  115,   64,  119,   63,  102,  120,
      120,  121,  121,  122,  122,   62,  118,   56,  125,  125,
       53,  117,  123,  123,   25,  120,   23,  121,   22,  122,
      123,  123,  124,  124,  125,  126,  126,    7,  123,    0,
      124,  124,  124,  122,  127,  127,    0,  120,  124,  125,
        0,  126,  128,  128,  129,  129,  124,    0,  125,    0,
      127,    0,  125,  130,  130,    0,  134,  134,  128,  132,
      129,  126,  132,  132,  133,  133,  132,  135,  135,  130,
        0,  132,  134,    0,  132,    0,  129,    0,  127,    0,
      133,    0,    0,  135,    0,  129,  134,    0,  128,    0,

      136,  136,  137,  137,  138,  138,  130,  131,  131,  139,
      139,  140,  140,  141,  141,  133,  136,    0,  137,    0,
      138,    0,  135,  131,    0,  139,    0,  140,    0,  141,
        0,  142,  142,    0,    0,    0,  143,  143,  131,  144,
      144,  131,  131,  136,    0,  131,  137,  142,    0,  138,
      131,  141,  143,  131,  139,  144,  145,  145,  146,  146,
      147,  147,  148,  148,  149,  149,  150,  150,  151,  151,
        0,    0,  145,    0,  146,    0,  147,    0,  148,    0,
      149,    0,  150,    0,  151,    0,  146,    0,  145,  152,
      152,    0,  147,  163,  163,  164,  164,    0,  150,  165,

      165,    0,  148,  166,  166,  152,    0,  149,    0,  163,
        0,  164,  167,  167,    0,  165,    0,  168,  168,  166,
      169,  169,  170,  170,  172,  172,    0,  164,  167,    0,
      152,  165,    0,  168,  173,  173,  169,    0,  170,    0,
      172,    0,  163,  174,  174,  175,  175,  176,  176,    0,
      173,  166,  168,  177,  177,  172,  178,  178,    0,  174,
        0,  175,    0,  176,    0,  173,    0,  179,  179,  177,
      180,  180,  178,  181,  181,    0,  182,  182,  174,  183,
      183,    0,  176,  179,    0,  175,  180,  184,  184,  181,
      178,  177,  182,    0,    0,  183,    0,  185,  185,  186,

      186,    0,    0,  184,  187,  187,  188,  188,  182,  181,
      189,  189,  179,  185,    0,  186,    0,  183,    0,  184,
      187,  182,  188,  191,  191,    0,  189,    0,  186,  185,
      190,  190,  184,  192,  192,    0,  193,  193,  188,  191,
      187,    0,  189,  194,  194,    0,  190,  195,  195,  192,
        0,  188,  193,  196,  196,  189,    0,  197,  197,  194,
        0,  192,  190,  195,  198,  198,  191,  199,  199,  196,
        0,  194,  193,  197,  200,  200,    0,  201,  201,  195,
      198,  202,  202,  199,    0,  203,  203,  204,  204,    0,
      200,    0,  197,  201,    0,  199,    0,  202,  205,  205,

      198,  203,    0,  204,  216,  216,    0,  201,  202,    0,
      217,  217,  218,  218,  205,  219,  219,  203,    0,  200,
      216,  220,  220,  222,  222,  205,  217,    0,  218,  223,
      223,  219,  224,  224,  225,  225,    0,  220,    0,  222,
      217,    0,  225,  225,    0,  223,  226,  226,  224,    0,
      225,    0,  218,  227,  227,  228,  228,  229,  229,    0,
      220,    0,  226,  230,  230,  231,  231,  232,  232,  227,
        0,  228,    0,  229,    0,  224,  233,  233,    0,  230,
        0,  231,    0,  232,  234,  234,  235,  235,    0,  226,
      236,  236,  233,  237,  237,  238,  238,  239,  239,    0,

      234,    0,  235,  240,  240,    0,  236,  241,  241,  237,
      230,  238,    0,  239,  242,  242,  243,  243,    0,  240,
      244,  244,    0,  241,  245,  245,    0,  246,  246,  236,
      242,    0,  243,  247,  247,    0,  244,  248,  248,    0,
      245,    0,  238,  246,  249,  249,  250,  250,    0,  247,
      251,  251,    0,  248,    0,  243,  252,  252,  253,  253,
      249,    0,  250,  247,  254,  254,  251,  246,    0,  245,
      255,  255,  252,    0,  253,    0,  249,    0,  250,    0,
      254,  256,  256,  267,  267,    0,  255,    0,  252,  268,
      268,  269,  269,  271,  271,  251,  254,  256,    0,  267,

      273,  273,    0,  253,    0,  268,    0,  269,    0,  271,
      274,  274,    0,  256,  272,  272,  273,  275,  275,  269,
      276,  276,  272,  272,  277,  277,  274,  278,  278,    0,
      272,  279,  279,  275,  268,    0,  276,  280,  280,    0,
      277,  281,  281,  278,  282,  282,    0,  279,  283,  283,
      284,  284,    0,  280,  285,  285,    0,  281,  286,  286,
      282,  279,  287,  287,  283,    0,  284,  298,  298,    0,
      285,  299,  299,    0,  286,  300,  300,  284,  287,  301,
      301,  281,  280,  298,  302,  302,    0,  299,  282,  303,
      303,  300,  304,  304,    0,  301,  305,  305,    0,    0,

      302,  306,  306,  315,  315,  303,  286,    0,  304,    0,
      287,  302,  305,    0,  299,  316,  316,  306,    0,  315,
      300,  317,  317,  318,  318,    0,  319,  319,  320,  320,
      304,  316,  321,  321,    0,  304,    0,  317,    0,  318,
      315,  305,  319,    0,  320,    0,  306,    0,  321,  329,
      329,  330,  330,  317,    0,  318,    0,  331,  331,    0,
      320,    0,  319,    0,  321,  329,    0,  330,  332,  332,
      333,  333,    0,  331,    0,  334,  334,  341,  341,  342,
      342,  343,  343,    0,  332,    0,  333,  344,  344,  330,
      331,  334,    0,  341,    0,  342,    0,  343,  345,  345,

        0,    0,  332,  344,  351,  351,  352,  352,    0,    0,
      333,  353,  353,    0,  345,  334,  343,    0,  344,    0,
      351,  341,  352,    0,  342,  354,  354,  353,    0,  345,
      355,  355,  357,  357,  358,  358,  351,    0,    0,    0,
        0,  354,    0,    0,    0,    0,  355,    0,  357,    0,
      358,    0,    0,    0,    0,    0,  353,  360,  360,  360,
      360,  360,  360,  361,  361,  361,  361,  361,  361,  362,
        0,  362,  362,  363,    0,  363,  364,  364,  365,  365,
      365,  365,  366,  366,  366,  366,  366,  366,  367,  367,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[96] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int smt_flex_debug;
int smt_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *smttext;
#line 1 "smtlexer.ll"
/*********************************************************************
Author: Roberto Bruttomesso <roberto.bruttomesso@gmail.com>

OpenSMT -- Copyright (C) 2009, Roberto Bruttomesso

OpenSMT is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenSMT is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenSMT. If not, see <http://www.gnu.org/licenses/>.
*********************************************************************/
#line 21 "smtlexer.ll"

#include <cstdio>
#include <cstdlib>
/* Keep the following headers in their original order */
#include "Egraph.h"
#include "smtparser.h"

#define BUFFER_LENGTH 1024

char   buffer[ BUFFER_LENGTH ];
char * pbuffer;
  


#line 942 "smtlexer.cc"

#define INITIAL 0
#define start_source 1
#define start_comment 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int smtlex_destroy (void );

int smtget_debug (void );

void smtset_debug (int debug_flag  );

YY_EXTRA_TYPE smtget_extra (void );

void smtset_extra (YY_EXTRA_TYPE user_defined  );

FILE *smtget_in (void );

void smtset_in  (FILE * in_str  );

FILE *smtget_out (void );

void smtset_out  (FILE * out_str  );

yy_size_t smtget_leng (void );

char *smtget_text (void );

int smtget_lineno (void );

void smtset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int smtwrap (void );
#else
extern int smtwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( smttext, smtleng, 1, smtout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( smtin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( smtin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, smtin))==0 && ferror(smtin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(smtin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int smtlex (void);

#define YY_DECL int smtlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after smttext and smtleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 41 "smtlexer.ll"


#line 1127 "smtlexer.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! smtin )
			smtin = stdin;

		if ( ! smtout )
			smtout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			smtensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				smt_create_buffer(smtin,YY_BUF_SIZE );
		}

		smt_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of smttext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 360 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1291 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < smtleng; ++yyl )
				if ( smttext[yyl] == '\n' )
					   
    smtlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 43 "smtlexer.ll"
{ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 44 "smtlexer.ll"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "smtlexer.ll"
{ return TK_BENCHMARK; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "smtlexer.ll"
{ return TK_EXTRASORTS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "smtlexer.ll"
{ return TK_EXTRAPREDS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "smtlexer.ll"
{ return TK_EXTRAFUNS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "smtlexer.ll"
{ return TK_ASSUMPTION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "smtlexer.ll"
{ return TK_FORMULA; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "smtlexer.ll"
{ return TK_INTERPOLATE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "smtlexer.ll"
{ return TK_SOURCE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "smtlexer.ll"
{ return TK_LOGIC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "smtlexer.ll"
{ return TK_STATUS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "smtlexer.ll"
{ return TK_CATEGORY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "smtlexer.ll"
{ return TK_DIFFICULTY; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "smtlexer.ll"
{ return TK_NOTES; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "smtlexer.ll"
{ return TK_U; }    
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "smtlexer.ll"
{ return TK_REAL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "smtlexer.ll"
{ return TK_INT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "smtlexer.ll"
{ return TK_BITVEC; }   
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "smtlexer.ll"
{ return TK_ARRAY; } 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "smtlexer.ll"
{ return TK_ARRAY_INDEX; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "smtlexer.ll"
{ return TK_ARRAY_ELEMENT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "smtlexer.ll"
{ return TK_REPEAT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "smtlexer.ll"
{ return TK_PLUS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "smtlexer.ll"
{ return TK_MINUS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "smtlexer.ll"
{ return TK_UMINUS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "smtlexer.ll"
{ return TK_TIMES; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "smtlexer.ll"
{ return TK_DIV; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "smtlexer.ll"
{ return TK_EQ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "smtlexer.ll"
{ return TK_LEQ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "smtlexer.ll"
{ return TK_GEQ; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "smtlexer.ll"
{ return TK_LT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "smtlexer.ll"
{ return TK_GT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "smtlexer.ll"
{ return TK_BVSLT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "smtlexer.ll"
{ return TK_BVSGT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "smtlexer.ll"
{ return TK_BVSLE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "smtlexer.ll"
{ return TK_BVSGE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "smtlexer.ll"
{ return TK_BVULT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "smtlexer.ll"
{ return TK_BVUGT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "smtlexer.ll"
{ return TK_BVULE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "smtlexer.ll"
{ return TK_BVUGE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "smtlexer.ll"
{ return TK_CONCAT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "smtlexer.ll"
{ return TK_EXTRACT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "smtlexer.ll"
{ return TK_BVAND; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "smtlexer.ll"
{ return TK_BVOR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "smtlexer.ll"
{ return TK_BVXOR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "smtlexer.ll"
{ return TK_BVNOT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "smtlexer.ll"
{ return TK_BVADD; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "smtlexer.ll"
{ return TK_BVSUB; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "smtlexer.ll"
{ return TK_BVMUL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "smtlexer.ll"
{ return TK_BVNEG; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "smtlexer.ll"
{ return TK_BVLSHR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "smtlexer.ll"
{ return TK_BVASHR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "smtlexer.ll"
{ return TK_BVSHL; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "smtlexer.ll"
{ return TK_BVSREM; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "smtlexer.ll"
{ return TK_BVUREM; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "smtlexer.ll"
{ return TK_BVSDIV; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "smtlexer.ll"
{ return TK_BVUDIV; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "smtlexer.ll"
{ return TK_ARRAY_SELECT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "smtlexer.ll"
{ return TK_ARRAY_STORE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "smtlexer.ll"
{ return TK_SIGN_EXTEND; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "smtlexer.ll"
{ return TK_ZERO_EXTEND; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "smtlexer.ll"
{ return TK_ROTATE_LEFT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "smtlexer.ll"
{ return TK_ROTATE_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "smtlexer.ll"
{ return TK_IMPLIES; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "smtlexer.ll"
{ return TK_AND; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "smtlexer.ll"
{ return TK_OR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "smtlexer.ll"
{ return TK_NOT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "smtlexer.ll"
{ return TK_IFF; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "smtlexer.ll"
{ return TK_XOR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "smtlexer.ll"
{ return TK_FLET; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "smtlexer.ll"
{ return TK_LET; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "smtlexer.ll"
{ return TK_TRUE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "smtlexer.ll"
{ return TK_FALSE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "smtlexer.ll"
{ return TK_ITE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "smtlexer.ll"
{ return TK_IFTHENELSE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 119 "smtlexer.ll"
{ return TK_DISTINCT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 120 "smtlexer.ll"
{ return TK_BIT0; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 121 "smtlexer.ll"
{ return TK_BIT1; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_NUM; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_BVNUM_NO_WIDTH; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_BVNUM; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_BVNUM; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_STR; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_FLET_STR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_LET_STR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 131 "smtlexer.ll"
{ smtlval.str = strdup( smttext ); return TK_ARGUMENT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "smtlexer.ll"
{ pbuffer = buffer; BEGIN(start_source); }
	YY_BREAK

case 89:
YY_RULE_SETUP
#line 136 "smtlexer.ll"
{ *pbuffer++ = '}'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 137 "smtlexer.ll"
{ *pbuffer++ = smttext[0]; }
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 138 "smtlexer.ll"
{ *pbuffer++ = '\n'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 139 "smtlexer.ll"
{ *pbuffer = '\0'; smtlval.str = strdup( buffer );
                   BEGIN(INITIAL); return TK_ARGUMENT; }
	YY_BREAK

case 93:
YY_RULE_SETUP
#line 143 "smtlexer.ll"
{ return *smttext; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 144 "smtlexer.ll"
{ printf( "Syntax error at line %d near %s\n", smtlineno, smttext ); exit( 1 ); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 146 "smtlexer.ll"
ECHO;
	YY_BREAK
#line 1701 "smtlexer.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(start_source):
case YY_STATE_EOF(start_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed smtin at a new source and called
			 * smtlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = smtin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( smtwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * smttext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of smtlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					smtrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			smtrestart(smtin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) smtrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 360 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 360 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 359);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					smtrestart(smtin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( smtwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve smttext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    smtlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void smtrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        smtensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            smt_create_buffer(smtin,YY_BUF_SIZE );
	}

	smt_init_buffer(YY_CURRENT_BUFFER,input_file );
	smt_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void smt_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		smtpop_buffer_state();
	 *		smtpush_buffer_state(new_buffer);
     */
	smtensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	smt_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (smtwrap()) processing, but the only time this flag
	 * is looked at is after smtwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void smt_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	smtin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE smt_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) smtalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in smt_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) smtalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in smt_create_buffer()" );

	b->yy_is_our_buffer = 1;

	smt_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with smt_create_buffer()
 * 
 */
    void smt_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		smtfree((void *) b->yy_ch_buf  );

	smtfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a smtrestart() or at EOF.
 */
    static void smt_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	smt_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then smt_init_buffer was _probably_
     * called from smtrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void smt_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		smt_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void smtpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	smtensure_buffer_stack();

	/* This block is copied from smt_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from smt_switch_to_buffer. */
	smt_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void smtpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	smt_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		smt_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void smtensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)smtalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in smtensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)smtrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in smtensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE smt_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) smtalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in smt_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	smt_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to smtlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       smt_scan_bytes() instead.
 */
YY_BUFFER_STATE smt_scan_string (yyconst char * yystr )
{
    
	return smt_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to smtlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE smt_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) smtalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in smt_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = smt_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in smt_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up smttext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		smttext[smtleng] = (yy_hold_char); \
		(yy_c_buf_p) = smttext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		smtleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int smtget_lineno  (void)
{
        
    return smtlineno;
}

/** Get the input stream.
 * 
 */
FILE *smtget_in  (void)
{
        return smtin;
}

/** Get the output stream.
 * 
 */
FILE *smtget_out  (void)
{
        return smtout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t smtget_leng  (void)
{
        return smtleng;
}

/** Get the current token.
 * 
 */

char *smtget_text  (void)
{
        return smttext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void smtset_lineno (int  line_number )
{
    
    smtlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see smt_switch_to_buffer
 */
void smtset_in (FILE *  in_str )
{
        smtin = in_str ;
}

void smtset_out (FILE *  out_str )
{
        smtout = out_str ;
}

int smtget_debug  (void)
{
        return smt_flex_debug;
}

void smtset_debug (int  bdebug )
{
        smt_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from smtlex_destroy(), so don't allocate here.
     */

    /* We do not touch smtlineno unless the option is enabled. */
    smtlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    smtin = stdin;
    smtout = stdout;
#else
    smtin = (FILE *) 0;
    smtout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * smtlex_init()
     */
    return 0;
}

/* smtlex_destroy is for both reentrant and non-reentrant scanners. */
int smtlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		smt_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		smtpop_buffer_state();
	}

	/* Destroy the stack itself. */
	smtfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * smtlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *smtalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *smtrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void smtfree (void * ptr )
{
	free( (char *) ptr );	/* see smtrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 146 "smtlexer.ll"



