itp:
	g++ -std=c++11 -o test_itp test_itp.cc -lopensmt2 -lgmp -lgmpxx -lz -lreadline -DPRODUCE_PROOF -DIGNORE_DL_THEORYPROPAGATION -DOSMT1_SUBSTITUTION -DCUSTOM_EL_ALLOC -DTERMS_HAVE_EXPLANATIONS -DUSE_GZ
